import {assemble,counts} from './model.js';
import {filterRows,summarize,sortRows,grouped,monthOf,exactDate} from './analytics.js';
import {reportLink} from './lib/coverage-intelligence.js';
const $=id=>document.getElementById(id),fmt=n=>n.toLocaleString('en-IN');
const keys=['from','to','kind','publisher','language','person','topic','search'],selectKeys=['kind','publisher','language','person','topic'];
let model,snapshot,filtered=[],page=1,busy=false;const size=20;
const palette=['#156ca2','#278367','#e4a24c','#809aa9','#8d78a6','#a3aab0'];
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function read(){return Object.fromEntries([...keys.map(k=>[k,$(k).value]),['undated',$('undated').checked]]);}
function stamp(s){return new Date(s).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});}
function urlState(){const u=new URL(location.href);for(const key of keys){const value=$(key).value;if(value)u.searchParams.set(key,value);else u.searchParams.delete(key);}if(!$('undated').checked)u.searchParams.set('undated','0');else u.searchParams.delete('undated');if(page>1)u.searchParams.set('page',page);else u.searchParams.delete('page');if($('sort').value!=='newest')u.searchParams.set('sort',$('sort').value);else u.searchParams.delete('sort');history.replaceState(null,'',u);}
function restore(){const p=new URLSearchParams(location.search);for(const key of keys){const value=p.get(key)||'';if(selectKeys.includes(key)&&value&&![...$(key).options].some(o=>o.value===value))$(key).add(new Option(value,value));$(key).value=value;}$('undated').checked=p.get('undated')!=='0';$('sort').value=['newest','oldest','publisher'].includes(p.get('sort'))?p.get('sort'):'newest';page=Math.max(1,Number.parseInt(p.get('page'))||1);}
function populate(){for(const key of selectKeys){const node=$(key),selected=node.value;while(node.options.length>1)node.remove(1);for(const [label] of counts(model.rows,key).sort((a,b)=>a[0].localeCompare(b[0])))node.add(new Option(label,label));if(selected&&![...node.options].some(o=>o.value===selected))node.add(new Option(selected,selected));node.value=selected;}}
function empty(box){box.append(el('p','No matching coverage. Try broadening your filters.','empty'));}
function bars(id,entries){const box=$(id);box.replaceChildren();if(!entries.length)return empty(box);const max=Math.max(...entries.map(e=>e[1]),1);for(const [label,n] of entries){const row=el('div'),cap=el('div',undefined,'bar-caption'),track=el('div',undefined,'track'),fill=el('div',undefined,'fill');cap.append(el('span',label),el('b',fmt(n)));fill.style.width=n/max*100+'%';track.append(fill);row.append(cap,track);box.append(row);}}
function columns(id,entries,year=false){const box=$(id);box.replaceChildren();if(!entries.length||!entries.some(e=>e[1]))return empty(box);const max=Math.max(...entries.map(e=>e[1]),1);for(const [label,n] of entries){const col=el('div',undefined,(year?'year-col':'column')+(n===max?' peak':'')),bar=el(year?'div':'i',undefined,year?'year-bar':undefined);bar.style.height=(n/max*180)+'px';col.append(el('b',fmt(n),year?'year-value':undefined),bar,el('span',label));col.title=`${label}: ${fmt(n)} coverage items`;box.append(col);}}
function donut(rows){const box=$('languages');box.replaceChildren();if(!rows.length)return empty(box);const entries=grouped(rows,'language',6),ring=el('div',undefined,'donut'),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 200 200');svg.setAttribute('aria-hidden','true');let offset=0;for(const [i,[label,n]] of entries.entries()){const c=document.createElementNS('http://www.w3.org/2000/svg','circle');for(const [k,v] of Object.entries({cx:100,cy:100,r:78,fill:'none',stroke:palette[i],'stroke-width':22,pathLength:100,'stroke-dasharray':`${n/rows.length*100} ${100-n/rows.length*100}`,'stroke-dashoffset':-offset}))c.setAttribute(k,v);svg.append(c);offset+=n/rows.length*100;}const center=el('div',undefined,'donut-center');center.append(el('b',fmt(rows.length)),el('span','coverage items'));ring.append(svg,center);const legend=el('div',undefined,'legend');for(const [i,[label,n]] of entries.entries()){const row=el('div',undefined,'legend-row'),dot=el('i'),value=el('b',fmt(n));dot.style.background=palette[i];value.append(el('small',(n/rows.length*100).toFixed(1)+'%'));row.append(dot,el('span',label),value);legend.append(row);}box.append(ring,legend);}
function matrix(rows,stats){const box=$('matrix');box.replaceChildren();if(!rows.length)return empty(box);const years=stats.years.map(e=>e[0]);if(stats.noYear)years.push('Unknown');const publishers=counts(rows,'publisher').slice(0,10),table=el('table',undefined,'heatmap'),head=el('thead'),hr=el('tr');for(const name of ['Publisher',...years,'Total']){const th=el('th',name);th.scope='col';hr.append(th);}head.append(hr);table.append(head);const body=el('tbody'),map=new Map();for(const r of rows){const key=JSON.stringify([r.publisher||'Not recorded',String(r.year||'Unknown')]);map.set(key,(map.get(key)||0)+1);}const max=Math.max(...map.values(),1);for(const [publisher,total] of publishers){const tr=el('tr'),th=el('th',publisher);th.scope='row';tr.append(th);for(const year of years){const n=map.get(JSON.stringify([publisher,year]))||0,td=el('td',n?fmt(n):'—');td.title=`${publisher}, ${year}: ${n} items`;if(n){const opacity=.08+.82*n/max;td.style.background=`rgb(21 108 162 / ${opacity})`;td.style.color=opacity>.5?'white':'#142e40';}tr.append(td);}tr.append(el('td',fmt(total)));body.append(tr);}table.append(body);box.append(table);}
function publication(r){const d=exactDate(r),m=monthOf(r);if(d)return new Date(d+'T00:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});if(m)return new Date(m+'-01T00:00:00Z').toLocaleDateString('en-GB',{month:'short',year:'numeric',timeZone:'UTC'});return r.year?`${r.year} · year only`:'Date unavailable';}
function renderTable(){const sorted=sortRows(filtered,$('sort').value),pages=Math.max(1,Math.ceil(sorted.length/size));page=Math.min(page,pages);const rows=$('rows');rows.replaceChildren();for(const r of sorted.slice((page-1)*size,page*size)){const tr=el('tr'),title=el('td'),headline=el('div',r.title||'Headline unavailable','headline');title.append(headline,el('span',r.id,'record-id'));const source=el('td'),url=reportLink(r.url);if(url){const a=el('a','Open ↗','source-link');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label',`Open source: ${r.title||r.id}`);source.append(a);}else source.append(el('span','Unavailable'));tr.append(el('td',publication(r)),title,el('td',r.publisher||'Not recorded'),el('td',r.language),el('td',r.kind),source);rows.append(tr);}if(!sorted.length){const td=el('td','No records match these filters.','empty');td.colSpan=6;const tr=el('tr');tr.append(td);rows.append(tr);}$('record-count').textContent=fmt(sorted.length);$('page-info').textContent=sorted.length?`${fmt((page-1)*size+1)}–${fmt(Math.min(page*size,sorted.length))} of ${fmt(sorted.length)} · Page ${page} of ${pages}`:'0 matching records';$('prev').disabled=page<=1;$('next').disabled=page>=pages;urlState();}
function render(){if(!model)return;const f=read();$('filter-error').hidden=!(f.from&&f.to&&f.from>f.to);$('filter-error').textContent='Choose a “To month” that is the same as or after “From month”.';filtered=filterRows(model.rows,f);const stats=summarize(filtered),pubs=counts(filtered,'publisher').filter(e=>!/^not recorded|unknown|publisher requires review$/i.test(e[0])),langs=counts(filtered,'language').filter(e=>!/^unknown|not recorded|language not recorded/i.test(e[0])),metrics=$('metrics');metrics.replaceChildren();for(const [i,[label,n,detail]] of [['Unique coverage',filtered.length,'Articles, unlinked clippings & e-papers'],['Publisher categories',pubs.length,'Recorded names · unknowns excluded'],['Language categories',langs.length,'Includes mixed-language categories'],['E-paper issues / sources',filtered.filter(r=>r.kind==='E-paper').length,'Included in the coverage total']].entries()){const card=el('article',undefined,'metric');card.append(el('span',String(i+1).padStart(2,'0'),'metric-index'),el('p',label),el('strong',fmt(n)),el('small',detail));metrics.append(card);}$('scope').textContent=`${fmt(filtered.length)} of ${fmt(model.rows.length)} items · all charts follow these filters`;columns('years',stats.years,true);$('year-note').textContent=`${fmt(stats.noYear)} items have no recorded year. Linked evidence is not counted twice.`;bars('publishers',counts(filtered,'publisher').slice(0,8));bars('people',grouped(filtered,'person',6));donut(filtered);columns('months',stats.monthly);columns('weekdays',stats.weekly);$('month-note').textContent=`${fmt(filtered.length-stats.noMonth)} items with a publication month · ${fmt(stats.noMonth)} without a month excluded.`;$('weekday-note').textContent=`${fmt(filtered.length-stats.noDay)} items with an exact date · ${fmt(stats.noDay)} without an exact date excluded.`;matrix(filtered,stats);renderTable();}
async function load(){if(busy)return;busy=true;$('refresh').disabled=true;$('refresh').textContent='Refreshing…';try{const res=await fetch('/api/dashboard');const body=await res.json();if(!res.ok)throw Error(body.error||'Archive unavailable');snapshot=body;model=assemble(body);populate();restore();render();const failed=body.connections.filter(c=>!c.ok);const version=body.connections.find(c=>c.name==='archive-version'&&c.ok)?.data;const mismatch=version?.dataHash&&body.data['archive-metadata']?.dataHash&&version.dataHash!==body.data['archive-metadata'].dataHash;$('status').className='status'+(body.stale||failed.length||mismatch?' warning':'');$('status').textContent=body.stale?'The latest refresh failed. Showing the last successful snapshot.':failed.length?`Published archive loaded. ${failed.length} live connections are unavailable; newer uploads or corrections may be missing. See data connections below.`:mismatch?'Repository data loaded. The deployed website uses a different archive version.':'Connected to the published archive. Charts update together as you filter.';$('checked').textContent='Last checked '+stamp(body.checkedAt);$('connections').replaceChildren(...body.connections.map(c=>el('li',`${c.name}: ${c.ok?'connected':'unavailable ('+c.error+')'}`)));$('version').textContent=`Source: public MCCIA archive · Commit ${body.commit.slice(0,8)} · ${fmt(model.linked)} linked clippings counted with their articles. ${mismatch?'Website version differs from this repository snapshot.':''}`;}catch(e){$('status').className='status error';$('status').textContent=model?'Refresh failed. Keeping the previously loaded figures. '+e.message:'Unable to load archive data. Check your connection and select Refresh data. '+e.message;if(!model)$('checked').textContent='Data unavailable — no totals loaded';}finally{busy=false;$('refresh').disabled=false;$('refresh').textContent='↻ Refresh data';}}
$('refresh').addEventListener('click',load);$('filters').addEventListener('submit',e=>e.preventDefault());$('filters').addEventListener('input',()=>{page=1;render();});$('filters').addEventListener('reset',()=>{setTimeout(()=>{for(const k of keys)$(k).value='';$('undated').checked=true;page=1;render();},0);});$('sort').addEventListener('change',()=>{page=1;renderTable();});for(const [id,step] of [['prev',-1],['next',1]])$(id).addEventListener('click',()=>{page+=step;renderTable();$('records').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});window.addEventListener('popstate',()=>{restore();render();});setInterval(()=>{if(!document.hidden)load();},300000);restore();load();
