import {authorizeEditor,editorRequired} from '../editor-auth';
import {pageRequest,pageResult} from '../pagination';
import {getStorageBindings} from '@/db';
import {validPublicationDate} from '@/app/media-metadata';
import records from '@/app/records.json' with {type:'json'};
import discoveries from '@/app/google-news-alerts.json' with {type:'json'};
import epapers from '@/app/epaper-sources.json' with {type:'json'};
export const dynamic='force-dynamic';
const known=new Set([...records,...discoveries,...epapers].map(r=>r.id));
async function database(){const {db}=getStorageBindings();await db.prepare('CREATE TABLE IF NOT EXISTS metadata_corrections (id TEXT PRIMARY KEY, patch TEXT NOT NULL, updated_at TEXT NOT NULL)').run();await db.prepare('CREATE TABLE IF NOT EXISTS metadata_correction_audit (id TEXT PRIMARY KEY, record_id TEXT NOT NULL, previous_patch TEXT, patch TEXT NOT NULL, actor TEXT NOT NULL, reason TEXT NOT NULL, created_at TEXT NOT NULL)').run();return db}
type Row={id:string;patch:string;updated_at:string};
export async function GET(request:Request){try{const db=await database(),{limit,before}=pageRequest(request);const rows=await db.prepare('SELECT * FROM metadata_corrections WHERE (? IS NULL OR updated_at < ? OR (updated_at = ? AND id < ?)) ORDER BY updated_at DESC,id DESC LIMIT ?').bind(before?.at??null,before?.at??null,before?.at??null,before?.id??null,limit+1).all<Row>();const page=pageResult(rows.results||[],limit,r=>r.updated_at,r=>r.id);return Response.json({records:page.records.map(r=>({id:r.id,patch:JSON.parse(r.patch),updatedAt:r.updated_at})),nextCursor:page.nextCursor},{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({error:'Correction storage is not connected.'},{status:503})}}
export async function POST(request:Request){const auth=await authorizeEditor(request);if(!auth.authorized)return editorRequired();let body:{id?:unknown;title?:unknown;date?:unknown;reason?:unknown;version?:unknown};try{const text=await request.text();if(text.length>5000)throw Error();body=JSON.parse(text);if(!body||typeof body!=='object'||Array.isArray(body))throw Error()}catch{return Response.json({error:'Invalid correction.'},{status:400})}const id=String(body.id||''),title=String(body.title||'').trim(),reason=String(body.reason||'').trim();if(!known.has(id))return Response.json({error:'Direct correction is available for indexed article records. Use Report an error for an unlinked clipping.'},{status:400});if(!title||title.length>1000||reason.length<10||reason.length>1500)return Response.json({error:'Provide a headline and a correction reason (10–1500 characters).'},{status:400});if(body.date!==undefined&&(typeof body.date!=='string'||(body.date!==''&&!validPublicationDate(body.date))))return Response.json({error:'Use a valid publication date that is not in the future, or leave it blank.'},{status:400});try{const db=await database(),previous=await db.prepare('SELECT * FROM metadata_corrections WHERE id = ?').bind(id).first<Row>();if((previous?.updated_at||'')!==String(body.version||''))return Response.json({error:'This article changed since you opened it. Reload before editing.'},{status:409});const patch={...(previous?JSON.parse(previous.patch):{}),title,...(body.date===undefined?{}:{date:body.date,year:body.date?Number(String(body.date).slice(0,4)):null,datePrecision:body.date?'day':'unavailable',publicationMonth:''})};const now=new Date().toISOString(),encoded=JSON.stringify(patch);const write=db.prepare('INSERT INTO metadata_corrections (id,patch,updated_at) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET patch=excluded.patch,updated_at=excluded.updated_at WHERE metadata_corrections.updated_at = ?').bind(id,encoded,now,previous?.updated_at||'');const audit=db.prepare('INSERT INTO metadata_correction_audit (id,record_id,previous_patch,patch,actor,reason,created_at) SELECT ?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM metadata_corrections WHERE id=? AND updated_at=?)').bind(crypto.randomUUID(),id,previous?.patch||null,encoded,auth.actor,reason,now,id,now);const result=await db.batch([write,audit]);if(!result[0]?.meta?.changes)return Response.json({error:'A newer correction was saved. Reload before editing.'},{status:409});return Response.json({id,patch,updatedAt:now})}catch{return Response.json({error:'The correction could not be saved. Check the storage connection.'},{status:503})}}
