'use client';
import {useEffect,useRef,useState} from 'react';
import {publicationLabel} from './archive-ui';
import {relatedStory,safeLink,type CoverageArticle} from './coverage-intelligence';
type Evidence={id:string;thumbnailUrl:string;originalImageUrl?:string;ocrText?:string|null;ocrExcerpt?:string|null;ocrReviewStatus?:string|null};
export default function ArticleView({article,evidence,records,onClose,onSelect}:{article:CoverageArticle;evidence:Evidence[];records:CoverageArticle[];onClose:()=>void;onSelect:(id:string)=>void}){
 const ref=useRef<HTMLDialogElement>(null),[kind,setKind]=useState('Incorrect date'),[details,setDetails]=useState('');
 useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close()},[]);
 const related=records.filter(r=>r.id!==article.id&&relatedStory(article,r)).slice(0,12);
 const body=`Record: ${article.id}\nHeadline: ${article.title.slice(0,100)}\nIssue: ${kind}\n\nSuggested correction and supporting source:\n${details}\n\nArchive: https://mccia-media.vercel.app/?search=${encodeURIComponent(article.id)}`;
 const reportUrl=`https://github.com/mcciaexplore-netizen/MCCIA-Media/issues/new?title=${encodeURIComponent(`Archive correction: ${article.id} — ${kind}`)}&body=${encodeURIComponent(body)}`;
 return <dialog ref={ref} className="article-dialog" onCancel={onClose} aria-labelledby="article-heading"><button className="article-close" onClick={onClose}>Close article</button><p>{article.id} · {article.publisher} · {publicationLabel(article)}</p><h2 id="article-heading">{article.title}</h2><p>{article.status||'Unverified'} · {article.topic||'Topic not assigned'}</p>{safeLink(article.url)&&<a href={safeLink(article.url)!} target="_blank" rel="noreferrer">Read on publisher website</a>}<div className="article-columns"><section><h3>Clipping evidence</h3>{evidence.length?evidence.map(c=><figure key={c.id}>{safeLink(c.originalImageUrl||c.thumbnailUrl)&&<a href={safeLink(c.originalImageUrl||c.thumbnailUrl)!} target="_blank" rel="noreferrer"><img src={safeLink(c.originalImageUrl||c.thumbnailUrl)!} alt={`Clipping evidence for ${article.title}`}/></a>}<figcaption>{c.originalImageUrl?'Original evidence':'Archive preview; original unavailable online'}</figcaption></figure>):safeLink(article.evidenceImageUrl)?<img src={safeLink(article.evidenceImageUrl)!} alt={`Evidence for ${article.title}`}/>:<p>No clipping image is available for this article.</p>}</section><section><h3>Extracted text</h3>{evidence.some(c=>c.ocrText||c.ocrExcerpt)?evidence.filter(c=>c.ocrText||c.ocrExcerpt).map(c=><div key={c.id}><p>{c.ocrReviewStatus||'OCR not editorially reviewed'}{!c.ocrText?' · Excerpt only; full transcription unavailable':''}</p><pre>{c.ocrText||c.ocrExcerpt}</pre></div>):<p>Full extracted text is unavailable for this record.</p>}{article.description&&<><h3>Archive description</h3><p className="article-description">{article.description}</p></>}</section></div><h3>Related coverage</h3>{related.length?<ul>{related.map(r=><li key={r.id}><button onClick={()=>onSelect(r.id)}>{r.title}</button> · {r.publisher}</li>)}</ul>:<p>No closely matching coverage found.</p>}<details className="error-report"><summary>Report an error</summary><label>Issue type<select value={kind} onChange={e=>setKind(e.target.value)}>{['Incorrect date','Incorrect headline','Duplicate record','Unrelated coverage','Other correction'].map(v=><option key={v}>{v}</option>)}</select></label><label>Correction and source<textarea maxLength={300} value={details} onChange={e=>setDetails(e.target.value)} placeholder="Explain the correction and include a supporting link."/></label><p>This opens a public GitHub report for the team. Sign in there and submit it to send the report. Do not include private information.</p><a href={reportUrl} target="_blank" rel="noreferrer">Continue to error report</a></details></dialog>;
}
