'use client';
import {useState,useSyncExternalStore} from 'react';
import type {CoverageArticle} from './coverage-intelligence';
const key='mccia-collections-v1';
function subscribe(callback:()=>void){window.addEventListener('storage',callback);window.addEventListener('collections-change',callback);return()=>{window.removeEventListener('storage',callback);window.removeEventListener('collections-change',callback)}}
function snapshot(){try{return localStorage.getItem(key)||'{}'}catch{return '{}'}}
function useCollections(){const raw=useSyncExternalStore(subscribe,snapshot,()=> '{}');let collections:Record<string,string[]>={};try{const value=JSON.parse(raw);if(value&&typeof value==='object'&&!Array.isArray(value))collections=Object.fromEntries(Object.entries(value).filter(([name,ids])=>name.length<=80&&Array.isArray(ids)).slice(0,30).map(([name,ids])=>[name,(ids as unknown[]).filter((id):id is string=>typeof id==='string'&&id.length<=100).slice(0,500)]))}catch{}return collections;}
function save(value:Record<string,string[]>){localStorage.setItem(key,JSON.stringify(value));window.dispatchEvent(new Event('collections-change'))}
export function CollectionPicker({id}:{id:string}){const collections=useCollections(),[name,setName]=useState(''),[message,setMessage]=useState('');function add(){const label=name.trim();if(!label)return;try{if(!Object.hasOwn(collections,label)&&Object.keys(collections).length>=30)throw Error('You can save up to 30 collections.');const items=collections[label]||[];if(items.length>=500&&!items.includes(id))throw Error('This collection has reached 500 articles.');save({...collections,[label]:[...new Set([...items,id])]});setMessage(`Saved to ${label} on this browser.`)}catch(error){setMessage(error instanceof Error?error.message:'Could not save collection.')}}return <details className="error-report"><summary>Save to collection</summary><p>Organise articles by event, campaign or topic. Collections are stored on this browser.</p><label>Collection name<input list="collection-names" maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><datalist id="collection-names">{Object.keys(collections).map(n=><option key={n} value={n}/>)}</datalist><button onClick={add} disabled={!name.trim()}>Save article</button><p role="status">{message}</p></details>}
export function CollectionShelf({records,onSelect}:{records:CoverageArticle[];onSelect:(id:string)=>void}){const collections=useCollections(),[error,setError]=useState('');return <details className="collection-shelf"><summary>My collections ({Object.keys(collections).length})</summary><p>Saved on this browser; collections do not sync between devices.</p>{Object.entries(collections).map(([name,ids])=><details key={name}><summary>{name} · {ids.length} articles</summary><ul>{ids.map(id=>{const r=records.find(row=>row.id===id);return <li key={id}><button disabled={!r} onClick={()=>onSelect(id)}>{r?.title||`${id} — unavailable in the current archive`}</button><button aria-label={`Remove ${id} from ${name}`} onClick={()=>{try{save({...collections,[name]:ids.filter(value=>value!==id)})}catch{setError('Could not update browser storage.')}}}>Remove</button></li>})}</ul></details>)}<p role="status">{error}</p></details>}
