'use client';
import {useEffect,useMemo,useState} from 'react';
import {counts,discoveredDay,groupStories,indiaDay,monthRows,previousMonth,publicationMonth,safeLink,type CoverageArticle} from './coverage-intelligence';
import {publicationLabel} from './archive-ui';
import collectionHistory from './collection-history.json';

type Health={checkedAt:string;discovery:{state:string;partial?:boolean;failedWatches?:number|null;lastRun?:string;lastSuccess?:string;runUrl?:string;lastFailure?:{date:string;url:string}|null};uploads:{state:string;message:string;failures?:number}};
const workflowUrl='https://github.com/mcciaexplore-netizen/MCCIA-Media/actions/workflows/weekly-google-news.yml';
export default function CoverageDesk({records}:{records:CoverageArticle[]}){
  const [tab,setTab]=useState('Daily digest'),[day,setDay]=useState(''),[month,setMonth]=useState(''),[health,setHealth]=useState<Health|null>(null),[healthError,setHealthError]=useState(false),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState(''),[showAll,setShowAll]=useState(false),[report,setReport]=useState<{url:string;month:string}|null>(null);
  useEffect(()=>()=>{if(report)URL.revokeObjectURL(report.url)},[report]);
  const months=useMemo(()=>[...new Set(records.map(publicationMonth).filter(Boolean))].sort().reverse(),[records]);
  const selectedMonth=month||months[0]||'2026-09';
  useEffect(()=>{let cancelled=false;const refresh=async()=>{try{const response=await fetch('/api/automation-status',{cache:'no-store'});if(!response.ok)throw new Error();const data=await response.json() as Health;if(!data.discovery||!data.uploads)throw new Error();if(!cancelled){setHealth(data);setDay(value=>value||indiaDay(data.checkedAt));setHealthError(false)}}catch{if(!cancelled)setHealthError(true)}};void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},300000);return()=>{cancelled=true;clearInterval(timer)}},[]);
  const digest=useMemo(()=>day?records.filter(r=>discoveredDay(r)===day):[],[records,day]);
  const latestDay=useMemo(()=>records.map(discoveredDay).filter(Boolean).sort().at(-1),[records]);
  const monthRecords=useMemo(()=>monthRows(records,selectedMonth),[records,selectedMonth]);
  const previous=useMemo(()=>monthRows(records,previousMonth(selectedMonth)),[records,selectedMonth]);
  const groups=useMemo(()=>groupStories(monthRecords).filter(g=>g.articles.length>1).sort((a,b)=>b.articles.length-a.articles.length),[monthRecords]);
  const trend=useMemo(()=>Array.from({length:12},(_,index)=>{let m=selectedMonth;for(let i=0;i<11-index;i++)m=previousMonth(m);return [m,monthRows(records,m).length] as [string,number]}),[records,selectedMonth]);
  const failures=health?.discovery.state==='failed'||health?.uploads.state==='attention';
  const delayed=health?.discovery.lastSuccess&&Date.parse(health.checkedAt)-Date.parse(health.discovery.lastSuccess)>36*3600000;
  async function exportMonth(){setExporting(true);setExportError('');try{const {monthlyWorkbook}=await import('./monthly-report');const bytes=await monthlyWorkbook(records,selectedMonth);setReport({url:URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),month:selectedMonth})}catch{setExportError('The report could not be generated. Please try again.')}finally{setExporting(false)}}
  return <section className="coverage-desk" id="coverage-desk" aria-labelledby="coverage-desk-title">
    <div className="desk-heading"><div><p className="kicker">YOUR MEDIA BRIEFING</p><h2 id="coverage-desk-title">Coverage desk</h2></div><p>Daily discoveries, related stories and monthly reports in one place.</p></div>
    <div className="desk-tabs" role="group" aria-label="Coverage desk sections">{['Daily digest','Story groups','Monthly insights','Collection history','System alerts'].map(label=><button key={label} className={tab===label?'active':''} aria-pressed={tab===label} onClick={()=>setTab(label)}>{label}{label==='System alerts'&&(failures||delayed)?' · attention':''}</button>)}</div>
    {(tab==='Story groups'||tab==='Monthly insights')&&<div className="desk-controls"><label>Publication month <select value={selectedMonth} onChange={e=>{setMonth(e.target.value);setShowAll(false)}}>{months.map(m=><option key={m}>{m}</option>)}</select></label><button disabled={exporting||!monthRecords.length} onClick={exportMonth}>{exporting?'Preparing report…':'Prepare Excel report'}</button>{report?.month===selectedMonth&&<a href={report.url} download={`MCCIA-coverage-${selectedMonth}.xlsx`}>Download Excel report</a>}<span role="status">{exportError}</span></div>}
    {tab==='Daily digest'&&<div><div className="desk-controls"><label>Discovery date <input type="date" value={day} max={health?indiaDay(health.checkedAt):undefined} onChange={e=>setDay(e.target.value)}/></label>{latestDay&&latestDay!==day&&<button onClick={()=>setDay(latestDay)}>Latest discoveries · {latestDay}</button>}</div><p>{digest.length} new coverage item{digest.length===1?'':'s'} recorded on {day||'the selected date'} · {new Set(digest.map(r=>r.publisher)).size} publishers.</p><p className="desk-note">Dates here show when items entered the discovery feed, not their publication date. Automatic discoveries remain unverified; open each source to check it.</p>{digest.length>0?<ul className="desk-stories">{digest.map(r=><li key={r.id}><ArticleLink item={r}/><small>{r.publisher} · Published {publicationLabel(r)} · {r.status||'Unverified'}</small></li>)}</ul>:<p className="desk-empty">No discoveries recorded for this date. This does not establish that no coverage was published. Check System alerts for the latest collection status.</p>}</div>}
    {tab==='Story groups'&&<div><p>{groups.length} suggested group{groups.length===1?'':'s'} in {selectedMonth}. Grouping uses article links or strongly similar headlines within three days. It does not merge or remove publisher coverage.</p><p className="desk-note">Cross-language story equivalence is not inferred from translated keywords alone.</p>{groups.length?groups.slice(0,showAll?groups.length:12).map(g=><details className="story-group" key={g.id}><summary>{g.articles[0].title}<small>{g.articles.length} articles · {new Set(g.articles.map(r=>r.publisher)).size} publishers</small></summary><ul className="desk-stories">{g.articles.map(r=><li key={r.id}><ArticleLink item={r}/><small>{r.publisher} · {publicationLabel(r)} · {r.id}</small></li>)}</ul></details>):<p className="desk-empty">No high-confidence headline or link groups found for this month. All articles remain searchable in the archive.</p>}{!showAll&&groups.length>12&&<button onClick={()=>setShowAll(true)}>Show all {groups.length} groups</button>}</div>}
    {tab==='Monthly insights'&&<div><div className="desk-stats"><p><strong>{monthRecords.length}</strong> coverage items</p><p><strong>{new Set(monthRecords.map(r=>r.publisher)).size}</strong> publishers</p><p><strong>{monthRecords.length-previous.length>=0?'+':''}{monthRecords.length-previous.length}</strong> vs {previousMonth(selectedMonth)}</p></div><p className="desk-note">Publication-month totals include linked evidence once and unlinked clippings separately. Missing dates are excluded. Current months may be incomplete; a change in archive coverage is not a measure of media sentiment.</p><div className="desk-insights"><div><h3>Coverage over 12 months</h3><CountBars rows={trend}/></div><div><h3>Leading topics this month</h3><CountBars rows={counts(monthRecords.map(r=>r.topic||'Topic not assigned')).slice(0,6)}/><h3>Leading publishers this month</h3><CountBars rows={counts(monthRecords.map(r=>r.publisher)).slice(0,6)}/></div></div></div>}
    {tab==='Collection history'&&<div><h3>Collection history</h3><p>Last successful workflow: {health?.discovery.lastSuccess?new Date(health.discovery.lastSuccess).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST':'Not available yet'}</p><p>History begins with the next collection after this feature was installed. Earlier item counts are not reconstructed.</p>{(collectionHistory as {checkedAt:string;state:string;newItems:number;totalItems:number;failedSources:string[]}[]).length?<ul className="desk-stories">{(collectionHistory as {checkedAt:string;state:string;newItems:number;totalItems:number;failedSources:string[]}[]).map(run=><li key={run.checkedAt}>{new Date(run.checkedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST · {run.state} · {run.newItems} added · {run.totalItems} discovery items{run.failedSources.length>0&&<p>Failed sources: {run.failedSources.join(', ')}</p>}</li>)}</ul>:<p>No collection entries recorded yet.</p>}<a href={workflowUrl} target="_blank" rel="noreferrer">View all workflow runs, including failed attempts</a></div>}
    {tab==='System alerts'&&<div aria-live="polite">{healthError?<p role="alert">Status check failed. Last displayed status may be outdated. <a href={workflowUrl} target="_blank" rel="noreferrer">Check discovery runs</a>.</p>:!health?<p>Checking automation…</p>:null}{health&&<><article className="desk-alert"><h3>Internet discovery · {health.discovery.state}</h3><p>Scheduled daily at 8:45 AM IST. {health.discovery.lastRun?`Latest run: ${new Date(health.discovery.lastRun).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST.`:'Run time unavailable.'}</p>{delayed&&<p role="alert">No successful discovery run has been recorded in the last 36 hours.</p>}{health.discovery.partial&&<p role="alert">The last published collection missed {health.discovery.failedWatches} news watch(es). Coverage may be incomplete.</p>}{health.discovery.state==='failed'&&<p role="alert">The latest discovery run did not complete successfully. New coverage may be missing.</p>}{health.discovery.lastFailure&&<p>Recent failed run: {indiaDay(health.discovery.lastFailure.date)}. <a href={health.discovery.lastFailure.url} target="_blank" rel="noreferrer">View run</a></p>}<a href={safeLink(health.discovery.runUrl)||workflowUrl} target="_blank" rel="noreferrer">View discovery status</a></article><article className="desk-alert"><h3>Automatic uploads · {health.uploads.state}</h3><p>{health.uploads.message}</p>{health.uploads.failures?<p>{health.uploads.failures} processing failure{health.uploads.failures===1?'':'s'} or stalled upload{health.uploads.failures===1?'':'s'} detected. Private submission details are not displayed.</p>:null}</article><p className="desk-note">Checked {new Date(health.checkedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST. Status refreshes every five minutes while this page is open. Errors before delivery reaches the website remain visible only in the Google Form script logs.</p></>}</div>}
  </section>;
}
function ArticleLink({item}:{item:CoverageArticle}){const link=safeLink(item.url)||safeLink(item.evidenceImageUrl);return link?<a href={link} target="_blank" rel="noreferrer">{item.title}</a>:<a href={`/?search=${encodeURIComponent(item.id)}#archive`}>{item.title}</a>}
function CountBars({rows}:{rows:[string,number][]}){const max=Math.max(1,...rows.map(([,n])=>n));return <div className="analytics-bars">{rows.map(([label,count])=><div key={label}><span>{label}</span><i><b style={{width:`${count/max*100}%`}}/></i><strong>{count}</strong></div>)}</div>}
