'use client';
import {useState} from 'react';
import type {CoverageArticle} from './coverage-intelligence';
export default function MetadataEditor({article,version}:{article:CoverageArticle;version?:string}){
 const [opened,setOpened]=useState(false),[configured,setConfigured]=useState<boolean|null>(null),[authenticated,setAuthenticated]=useState(false),[key,setKey]=useState(''),[title,setTitle]=useState(article.title),[date,setDate]=useState(article.date),[changeDate,setChangeDate]=useState(false),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function open(){setOpened(true);try{const response=await fetch('/api/editor-session',{cache:'no-store'});if(!response.ok)throw Error();const data=await response.json() as {configured:boolean;authenticated:boolean};setConfigured(data.configured===true);setAuthenticated(data.authenticated===true)}catch{setMessage('Editor access could not be checked.')}}
 async function login(){setBusy(true);try{const r=await fetch('/api/editor-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})}),data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error);setAuthenticated(true);setKey('');setMessage('Editor signed in.')}catch(e){setMessage(e instanceof Error?e.message:'Sign-in failed.')}finally{setBusy(false)}}
 async function save(){setBusy(true);try{const r=await fetch('/api/corrections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:article.id,title,...(changeDate?{date}:{}),reason,version:version||''})}),data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error);window.dispatchEvent(new CustomEvent('mccia-corrections-updated'));setMessage('Correction saved. The archive is refreshing.')}catch(e){setMessage(e instanceof Error?e.message:'Save failed.')}finally{setBusy(false)}}
 if(!opened)return <button onClick={open}>Team metadata correction</button>;
 return <section className="error-report"><h3>Team metadata correction</h3>{configured===false?<p>Direct editing is not configured. An administrator must connect storage and enable editor access. Use Report an error meanwhile.</p>:!authenticated?<><p>Authorised team members only.</p><label>Editor access key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/></label><button disabled={busy||!key||configured!==true} onClick={login}>Sign in</button></>:<><label>Corrected headline<input maxLength={1000} value={title} onChange={e=>setTitle(e.target.value)}/></label><label><span><input type="checkbox" checked={changeDate} onChange={e=>setChangeDate(e.target.checked)}/> Change publication date</span></label>{changeDate&&<label>Corrected publication date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/><small>Leave blank only when the publication date is unknown.</small></label>}<label>Reason and supporting source<textarea maxLength={1500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||reason.trim().length<10||!title.trim()} onClick={save}>{busy?'Saving…':'Save correction'}</button><button disabled={busy} onClick={async()=>{const r=await fetch('/api/editor-session',{method:'DELETE'});if(r.ok)setAuthenticated(false);else setMessage('Sign-out failed. Try again.')}}>Sign out</button></>}<p role="status">{message}</p></section>;
}
