'use client';
import { useMemo, useState } from 'react';
import recordsData from './records.json';

type RecordItem={id:string;date:string;year:number;type:string;format:string;publisher:string;title:string;language:string;presence:string;topic:string;description:string;status:string;url?:string|null;mediaUrl?:string|null;notes:string};
const records=recordsData as RecordItem[];
const typeLetters:Record<string,string>={Article:'A',Video:'V',PDF:'P',Image:'I',Social:'S',Other:'O'};
const fallbackImages:Record<string,string>={Article:'/fallbacks/article.webp',Social:'/fallbacks/social.webp',PDF:'/fallbacks/pdf.webp',Video:'/fallbacks/video.webp',Image:'/fallbacks/image.webp',Other:'/fallbacks/other.webp'};
const options=(values:string[])=>[...new Set(values)].sort((a,b)=>a.localeCompare(b));
const prettyDate=(value:string)=>value?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T00:00:00`)):'Date not recorded';
const contentImage=(item:RecordItem)=>{const text=`${item.title} ${item.topic} ${item.description} ${item.presence}`.toLowerCase();const themes:[string[],string][]=[
  [['covid','oxygen','vayu','health','hospital','medical','vaccin','pandemic','bipap'],'/themes/healthcare.webp'],
  [['defence','defense','aerospace','army','military','drone','indigeni','electronics','semiconductor','radar'],'/themes/defence.webp'],
  [['agri','farm','food processing','nabard','crop','rural','horticulture','export facilitation centre'],'/themes/agriculture.webp'],
  [['artificial intelligence',' ai ','machine learning','automation','digital','cyber','technology','innovation lab','hackathon'],'/themes/ai.webp'],
  [['education','student','skill','training','fellowship','university','college','academic','entrepreneurship'],'/themes/education.webp'],
  [['international','export','import','trade delegation','pibs','business summit','global','embassy','consul','buyer-seller'],'/themes/trade.webp'],
  [['budget','policy','government','survey','infrastructure','tariff','tax','power','msedcl','lockdown','economy'],'/themes/policy.webp'],
  [['award','conference','conclave','summit','expo','exhibition','event','inaugurat','ceremony'],'/themes/events.webp'],
  [['director general','leadership','president','interview','address','speaker','profile','board','committee'],'/themes/leadership.webp'],
  [['msme','manufactur','industry','factory','industrial','startup','production','supply chain','business growth'],'/themes/manufacturing.webp'],
];for(const [words,image] of themes)if(words.some(word=>text.includes(word)))return image;return fallbackImages[item.type]||fallbackImages.Other};

export default function Home(){
  const [search,setSearch]=useState(''); const [year,setYear]=useState('All'); const [publisher,setPublisher]=useState('All'); const [type,setType]=useState('All'); const [language,setLanguage]=useState('All'); const [topic,setTopic]=useState('All'); const [status,setStatus]=useState('All'); const [sort,setSort]=useState('Newest'); const [view,setView]=useState<'grid'|'list'>('grid'); const [showFilters,setShowFilters]=useState(false);
  const years=options(records.filter(r=>r.year>0).map(r=>String(r.year))).sort((a,b)=>Number(b)-Number(a)); const publishers=options(records.map(r=>r.publisher)); const types=options(records.map(r=>r.type)); const languages=options(records.map(r=>r.language)); const topics=options(records.map(r=>r.topic));
  const active=[search,year,publisher,type,language,topic,status].filter((value,index)=>index===0?Boolean(value):value!=='All').length;
  const reset=()=>{setSearch('');setYear('All');setPublisher('All');setType('All');setLanguage('All');setTopic('All');setStatus('All')};
  const results=useMemo(()=>{const term=search.trim().toLowerCase(); const filtered=records.filter(r=>(year==='All'||String(r.year)===year)&&(publisher==='All'||r.publisher===publisher)&&(type==='All'||r.type===type)&&(language==='All'||r.language===language)&&(topic==='All'||r.topic===topic)&&(status==='All'||r.status===status)&&(!term||`${r.title} ${r.publisher} ${r.topic} ${r.description} ${r.presence} ${r.notes}`.toLowerCase().includes(term))); return filtered.sort((a,b)=>sort==='Oldest'?a.date.localeCompare(b.date):sort==='Publisher'?a.publisher.localeCompare(b.publisher):b.date.localeCompare(a.date))},[search,year,publisher,type,language,topic,status,sort]);
  const exportCsv=()=>{const columns=['ID','Date','Year','Type','Publisher','Title','Language','DG presence','Topic','Description','Verification','Source URL']; const rows=results.map(r=>[r.id,r.date,r.year,r.format,r.publisher,r.title,r.language,r.presence,r.topic,r.description,r.status,r.url||'']); const csv=[columns,...rows].map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\n'); const link=document.createElement('a'); link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); link.download='mccia-media-filtered.csv'; link.click(); URL.revokeObjectURL(link.href)};
  return <main id="top">
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">M</span><span><strong>MCCIA</strong><small>Media Intelligence</small></span></a><nav><a className="nav-active" href="#archive">Archive</a><a href="#method">Method</a></nav><div className="header-actions"><span>Updated 25 Aug 2026</span><button onClick={exportCsv}>Export CSV</button></div></header>
    <section className="masthead"><div><p className="kicker">PUBLIC COVERAGE ARCHIVE / 2018 TO 2026</p><h1>Every public mention,<br/>one searchable record.</h1><p className="intro">News, interviews, photographs, videos, social posts and official documents concerning MCCIA Director General Prashant Girbane.</p></div><div className="metrics" aria-label="Archive summary"><div><strong>{records.length}</strong><span>Structured records</span></div><div><strong>{records.filter(r=>r.status==='Verified').length}</strong><span>Verified sources</span></div><div><strong>{publishers.length}</strong><span>Publishers</span></div><div><strong>{languages.length}</strong><span>Languages</span></div></div></section>
    <section className="workspace" id="archive"><button className="mobile-filter" onClick={()=>setShowFilters(v=>!v)}>Refine archive {active>0&&<span>{active}</span>}</button>
      <aside className={`filters ${showFilters?'filters-open':''}`}><div className="filter-heading"><div><strong>Refine archive</strong><small>{active?`${active} active`:'All records'}</small></div><button onClick={reset}>Clear all</button></div>
        <label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, headline, topic..."/></label>
        <label>Year<select value={year} onChange={e=>setYear(e.target.value)}><option>All</option>{years.map(v=><option key={v}>{v}</option>)}</select></label>
        <label>News channel<select value={publisher} onChange={e=>setPublisher(e.target.value)}><option>All</option>{publishers.map(v=><option key={v}>{v}</option>)}</select></label>
        <fieldset><legend>Media type</legend><div className="type-grid"><button className={type==='All'?'selected':''} onClick={()=>setType('All')}>All</button>{types.map(v=><button key={v} className={type===v?'selected':''} onClick={()=>setType(v)}>{v}</button>)}</div></fieldset>
        <label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}><option>All</option>{languages.map(v=><option key={v}>{v}</option>)}</select></label>
        <label>Topic<select value={topic} onChange={e=>setTopic(e.target.value)}><option>All</option>{topics.map(v=><option key={v}>{v}</option>)}</select></label>
        <fieldset><legend>Verification</legend>{['All','Verified','Partially verified','Unverified'].map(v=><label className="radio-row" key={v}><input type="radio" name="status" checked={status===v} onChange={()=>setStatus(v)}/><span>{v}</span></label>)}</fieldset>
        <div className="archive-note"><strong>Evidence labels</strong><p>Verified records have a direct accessible source. Leads without a source remain visible as unverified.</p></div>
      </aside>
      <div className="results-panel"><div className="results-toolbar"><div><strong>{results.length} result{results.length===1?'':'s'}</strong><span>{active?'Filtered view':'Complete structured index'}</span></div><div className="toolbar-controls"><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option>Newest</option><option>Oldest</option><option>Publisher</option></select></label><div className="view-toggle" aria-label="View style"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')}>Grid</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}>List</button></div></div></div>
        {results.length?<div className={`card-grid ${view==='list'?'list-view':''}`}>{results.map(item=>{const fallback=contentImage(item);return <article className="media-card" key={item.id}><div className={`media-visual visual-${item.type.toLowerCase()} has-image ${item.mediaUrl?'':'generated-image'}`}><img src={item.mediaUrl||fallback} alt="" loading="lazy" referrerPolicy="no-referrer" onError={e=>{if(e.currentTarget.src.endsWith(fallback))return;e.currentTarget.src=fallback;e.currentTarget.parentElement?.classList.add('generated-image')}}/><span className="media-letter">{typeLetters[item.type]||'O'}</span><span className="media-type">{item.type}</span>{!item.mediaUrl&&<span className="illustration-label">Illustration</span>}<span className="record-id">{item.id}</span></div><div className="card-body"><div className="card-meta"><span>{item.publisher}</span><time>{prettyDate(item.date)}</time></div><h2>{item.title}</h2><p>{item.description}</p><div className="tags"><span>{item.language}</span><span>{item.topic}</span><span>{item.presence}</span></div><div className="card-footer"><span className={`status status-${item.status.toLowerCase().replaceAll(' ','-')}`}>{item.status}</span>{item.url?<a href={item.url} target="_blank" rel="noreferrer">Open original source</a>:<span className="missing">Source URL not located</span>}</div></div></article>})}</div>:<div className="empty-state"><strong>No matching records</strong><p>Try a broader phrase or clear one of the active filters.</p><button onClick={reset}>Show all records</button></div>}
      </div>
    </section>
    <footer id="method"><p><strong>MCCIA Media Intelligence</strong><br/>A research dashboard that keeps confirmed sources and unresolved leads in one auditable archive.</p><p>Verification labels describe source availability, not an endorsement of every statement in an article or post.</p><a href="https://www.mcciapune.com/mcciaadmin/team_tab/" target="_blank" rel="noreferrer">Official MCCIA profile</a></footer>
  </main>;
}
