'use client';
import { useMemo, useState } from 'react';

type MediaType = 'Article' | 'Video' | 'PDF' | 'Image' | 'Social';
type Status = 'Verified' | 'Partially verified' | 'Unverified';
type RecordItem = { id:number; date:string; year:number; title:string; publisher:string; type:MediaType; status:Status; language:'English'|'Marathi'; presence:string[]; topic:string; description:string; url?:string; image?:string };

const records: RecordItem[] = [
  {id:1,date:'30 Dec 2024',year:2024,title:'Growth in MSME, emergence as defence manufacturing hub',publisher:'The Indian Express',type:'Article',status:'Verified',language:'English',presence:['Authored','Photo','Named'],topic:'MSME & Defence',description:'A year-end analysis authored by Prashant Girbane on Pune industry, MSME growth and the region’s defence manufacturing ecosystem.',url:'https://indianexpress.com/article/cities/pune/growth-msme-defence-manufacturing-hub-pune-inc-9751812/',image:'https://images.indianexpress.com/2024/12/MCCIA.jpg'},
  {id:2,date:'17 Feb 2026',year:2026,title:'MCCIA to set up ₹10-crore Drone Innovation Centre',publisher:'The Indian Express',type:'Article',status:'Verified',language:'English',presence:['Quoted','Named'],topic:'Drones & MSME',description:'Girbane outlines shared design, simulation, prototyping and testing support for MSMEs and drone startups in Pune.',url:'https://indianexpress.com/article/cities/pune/mccia-drone-innovation-centre-pune-msmes-food-technology-cfc-10536121/'},
  {id:3,date:'07 Mar 2026',year:2026,title:'West Asia conflict to hit nearly half of Pune industries',publisher:'The Indian Express',type:'Article',status:'Verified',language:'English',presence:['Quoted','Named'],topic:'Trade & Supply Chain',description:'MCCIA survey of 68 companies, with Girbane discussing crude oil, polymers, Gulf shipping routes and temporary uncertainty.',url:'https://indianexpress.com/article/cities/pune/west-asia-conflict-to-hit-nearly-half-of-pune-industries-mccia-survey-10569838/'},
  {id:4,date:'12 Jan 2019',year:2019,title:'Technology can help manufacturing sector enormously',publisher:'Hindustan Times',type:'Article',status:'Verified',language:'English',presence:['Interview','Photo','Named'],topic:'Manufacturing',description:'A dedicated interview with MCCIA’s Director General about matching new technology with practical manufacturing needs.',url:'https://www.hindustantimes.com/pune-news/technology-can-help-manufacturing-sector-enormously-if-the-needs-are-matched-says-prashant-girbane-director-general-mccia/story-PM5y2YwwAlQ8By8Wm9w7CJ.html'},
  {id:5,date:'29 Nov 2025',year:2025,title:'MCCIA helpline and AI lab enable MSMEs to grow',publisher:'Times of India',type:'Article',status:'Verified',language:'English',presence:['Quoted','Named'],topic:'AI & MSME',description:'Detailed coverage of the statewide helpline, 55 experts and MCCIA’s applied AI support for hundreds of smaller firms.',url:'https://timesofindia.indiatimes.com/city/pune/mccia-helpline-and-ai-lab-enable-msmes-to-grow-their-businesses/amp_articleshow/125645820.cms'},
  {id:6,date:'20 Feb 2025',year:2025,title:'MCCIA to host International Business Summit 2025',publisher:'Times of India',type:'Article',status:'Verified',language:'English',presence:['Quoted','Named'],topic:'Investment & GCC',description:'Girbane speaks about international investment interest, Pune’s automotive base and the rise of Global Capability Centres.',url:'https://timesofindia.indiatimes.com/city/pune/mccia-to-host-international-business-summit-2025-on-feb-24-25/articleshow/118395785.cms'},
  {id:7,date:'03 Jan 2024',year:2024,title:'Defence Manufacturer Directory’s third edition launched',publisher:'Free Press Journal',type:'Image',status:'Verified',language:'English',presence:['Photo','Named'],topic:'Defence',description:'Girbane appears at Southern Command headquarters for the launch of MCCIA’s directory covering 650 defence industries.',url:'https://www.freepressjournal.in/pune/pune-defence-manufacturer-directorys-3rd-edition-launched-at-southern-command-hq'},
  {id:8,date:'Nov 2025',year:2025,title:'MCCIA’s role in building India’s semiconductor future',publisher:'MCCIA',type:'PDF',status:'Verified',language:'English',presence:['Speech','Photo','Named'],topic:'Semiconductors',description:'Conference report containing Girbane’s welcome address, MCCIA activity metrics and event photography.',url:'https://www.mcciapune.com/media/Publication/Publication_File/MCCIA_SEC_Report_2025_Proof_18-11-25.pdf'},
  {id:9,date:'Nov 2024',year:2024,title:'Semiconductor Ecosystem Conference 2024',publisher:'MCCIA',type:'PDF',status:'Verified',language:'English',presence:['Speech','Photo','Named'],topic:'Semiconductors',description:'Official report with Girbane’s opening remarks on Pune’s industrial clusters and electronics manufacturing capability.',url:'https://www.mcciapune.com/media/Publication/Publication_File/MCCIA_SEC_Report_2024_FINAL_PDF_22-11-2024.pdf'},
  {id:10,date:'Mar 2021',year:2021,title:'Sampada editorial and publisher declaration',publisher:'MCCIA Sampada',type:'PDF',status:'Verified',language:'English',presence:['Authored','Photo','Named'],topic:'MCCIA Publication',description:'MCCIA’s magazine includes an editorial signed by Girbane, his portrait and publication details.',url:'https://www.mcciapune.com/media/Publication/Publication_File/Sampada_Final_March.pdf'},
  {id:11,date:'01 Feb 2020',year:2020,title:'Prashant Girbane responds to Union Budget 2020',publisher:'Loksatta',type:'Video',status:'Verified',language:'Marathi',presence:['Video','Interview','Named'],topic:'Union Budget',description:'A Marathi video interview capturing Girbane’s immediate reaction to the Union Budget.',url:'https://www.loksatta.com/videos/vishesh-vartankan/2074647/budget-2020-prashant-girbane-pune/'},
  {id:12,date:'30 Nov 2025',year:2025,title:'तुमच्या उद्योगासमोर अडचणी आहेत?',publisher:'Loksatta',type:'Article',status:'Verified',language:'Marathi',presence:['Quoted','Named'],topic:'MSME Helpline',description:'Marathi coverage of MCCIA’s helpline and expert guidance programme for MSMEs across Maharashtra.',url:'https://www.loksatta.com/pune/are-there-any-problems-facing-your-industry-now-maratha-chamber-will-help-you-solve-them-pune-print-news-ssb-93-5541640/'},
  {id:13,date:'23 Jul 2021',year:2021,title:'Cluster development needs more focussed attention',publisher:'Moneycontrol',type:'Article',status:'Verified',language:'English',presence:['Authored','Named'],topic:'MSME Policy',description:'A co-authored opinion article proposing six measures to improve cluster development and regional growth.',url:'https://www.moneycontrol.com/news/opinion/cluster-development-needs-more-focussed-attention-7213441.html'},
  {id:14,date:'27 Feb 2023',year:2023,title:'IIM-A alumnus meets Narayana Murthy',publisher:'Business Today',type:'Social',status:'Verified',language:'English',presence:['Named','Social post'],topic:'Leadership',description:'Coverage based on Girbane’s public account of a chance meeting with Infosys founder N.R. Narayana Murthy.',url:'https://www.businesstoday.in/latest/corporate/story/iim-ahmedabad-alumnus-meets-narayana-murthy-infosys-founder-shares-fond-memories-371658-2023-02-27//'},
  {id:15,date:'Jul 2024',year:2024,title:'Hosting MeitY Secretary S. Krishnan at SEC 2024',publisher:'LinkedIn',type:'Social',status:'Partially verified',language:'English',presence:['Photo','Named'],topic:'Semiconductors',description:'The conference is confirmed in MCCIA’s official report, but the individual LinkedIn post URL remains missing.'},
  {id:16,date:'Dec 2022',year:2022,title:'Meeting Finance Minister Nirmala Sitharaman',publisher:'LinkedIn',type:'Image',status:'Unverified',language:'English',presence:['Claimed photo'],topic:'Government Meeting',description:'Claimed discussion about GSTN and TReDS integration. The supplied research did not include a direct post URL.'},
  {id:17,date:'Apr 2023',year:2023,title:'Army Chief’s Conclave with defence leadership',publisher:'LinkedIn',type:'Image',status:'Unverified',language:'English',presence:['Claimed photo'],topic:'Defence',description:'Claimed photograph with Rajnath Singh and Gen. Manoj Pande. The original post has not yet been located.'},
  {id:18,date:'May 2026',year:2026,title:'TEDxPune sustainable-growth talk',publisher:'TEDxPune',type:'Video',status:'Partially verified',language:'English',presence:['Speaker listing'],topic:'Sustainability',description:'Girbane’s speaker listing is public; the claimed talk title, date and complete recording still need verification.',url:'https://www.tedxpune.com/speakers'},
];

const initials: Record<MediaType,string> = {Article:'A',Video:'V',PDF:'P',Image:'I',Social:'S'};

export default function Home() {
  const [search,setSearch]=useState(''); const [year,setYear]=useState('All'); const [publisher,setPublisher]=useState('All'); const [type,setType]=useState('All'); const [status,setStatus]=useState('All'); const [sort,setSort]=useState('Newest'); const [showFilters,setShowFilters]=useState(false);
  const years=[...new Set(records.map(i=>i.year))].sort((a,b)=>b-a); const publishers=[...new Set(records.map(i=>i.publisher))].sort(); const types=[...new Set(records.map(i=>i.type))];
  const results=useMemo(()=>{const term=search.trim().toLowerCase(); return records.filter(i=>(year==='All'||i.year===Number(year))&&(publisher==='All'||i.publisher===publisher)&&(type==='All'||i.type===type)&&(status==='All'||i.status===status)&&(!term||`${i.title} ${i.publisher} ${i.topic} ${i.description} ${i.presence.join(' ')}`.toLowerCase().includes(term))).sort((a,b)=>sort==='Oldest'?a.year-b.year:b.year-a.year)},[search,year,publisher,type,status,sort]);
  const reset=()=>{setSearch('');setYear('All');setPublisher('All');setType('All');setStatus('All')};
  const activeCount=[year,publisher,type,status].filter(v=>v!=='All').length+(search?1:0);
  return <main>
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">M</span><span><strong>MCCIA</strong><small>Media Monitor</small></span></a><nav><a className="nav-active" href="#archive">Archive</a><a href="#about">About</a></nav><span className="updated">Updated 24 Aug 2026</span></header>
    <section className="masthead" id="top"><div><p className="kicker">PUBLIC COVERAGE ARCHIVE · 2018–2026</p><h1>Prashant Girbane<br/>in the public record</h1><p className="intro">News, interviews, photographs, videos and official documents concerning MCCIA’s Director General, gathered with direct source access.</p></div><div className="metrics"><div><strong>{records.length}</strong><span>Indexed records</span></div><div><strong>{records.filter(r=>r.status==='Verified').length}</strong><span>Verified sources</span></div><div><strong>{publishers.length}</strong><span>Publishers</span></div></div></section>
    <section className="workspace" id="archive"><button className="mobile-filter" onClick={()=>setShowFilters(!showFilters)}>Filters {activeCount>0&&<span>{activeCount}</span>}</button>
      <aside className={`filters ${showFilters?'filters-open':''}`}><div className="filter-heading"><strong>Refine archive</strong><button onClick={reset}>Reset</button></div>
        <label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Title, topic, quote…"/></label>
        <label>Year<select value={year} onChange={e=>setYear(e.target.value)}><option>All</option>{years.map(v=><option key={v}>{v}</option>)}</select></label>
        <label>News channel<select value={publisher} onChange={e=>setPublisher(e.target.value)}><option>All</option>{publishers.map(v=><option key={v}>{v}</option>)}</select></label>
        <fieldset><legend>Media type</legend><div className="type-grid"><button className={type==='All'?'selected':''} onClick={()=>setType('All')}>All</button>{types.map(v=><button key={v} className={type===v?'selected':''} onClick={()=>setType(v)}>{v}</button>)}</div></fieldset>
        <fieldset><legend>Verification</legend>{(['All','Verified','Partially verified','Unverified'] as const).map(v=><label className="radio-row" key={v}><input type="radio" name="status" checked={status===v} onChange={()=>setStatus(v)}/><span>{v}</span></label>)}</fieldset>
        <div className="archive-note"><strong>Evidence standard</strong><p>Verified records have an accessible source confirming the name, quotation, image or appearance.</p></div>
      </aside>
      <div className="results-panel"><div className="results-toolbar"><div><strong>{results.length} results</strong><span>{activeCount?`${activeCount} active filter${activeCount>1?'s':''}`:'Showing the complete index'}</span></div><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option>Newest</option><option>Oldest</option></select></label></div>
        {results.length?<div className="card-grid">{results.map(item=><article className="media-card" key={item.id}><div className={`media-visual visual-${item.type.toLowerCase()}`}>{item.image&&<img src={item.image} alt="" onError={e=>{e.currentTarget.style.display='none'}}/>}<span className="media-letter">{initials[item.type]}</span><span className="media-type">{item.type}</span></div><div className="card-body"><div className="card-meta"><span>{item.publisher}</span><time>{item.date}</time></div><h2>{item.title}</h2><p>{item.description}</p><div className="tags">{item.presence.slice(0,3).map(tag=><span key={tag}>{tag}</span>)}</div><div className="card-footer"><span className={`status status-${item.status.toLowerCase().replace(' ','-')}`}>{item.status}</span>{item.url?<a href={item.url} target="_blank" rel="noreferrer">Open source ↗</a>:<span className="missing">Source URL missing</span>}</div></div></article>)}</div>:<div className="empty-state"><strong>No records match these filters</strong><p>Clear the filters or try a broader search term.</p><button onClick={reset}>Show all records</button></div>}
      </div>
    </section>
    <footer id="about"><p><strong>MCCIA Media Monitor</strong> is a research prototype. Verification labels distinguish confirmed sources from leads that still require review.</p><a href="https://www.mcciapune.com/mcciaadmin/team_tab/" target="_blank" rel="noreferrer">Official MCCIA profile ↗</a></footer>
  </main>;
}
