'use client';
import {useState,useMemo,useEffect} from 'react';
import {publicationMonth,reportRevision,type CoverageArticle} from './coverage-intelligence';
export default function ReportBuilder({records}:{records:CoverageArticle[]}){
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[topic,setTopic]=useState('All'),[publisher,setPublisher]=useState('All'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<{url:string;key:string}|null>(null);
 const [ready,setReady]=useState(false);
 useEffect(()=>{const restore=()=>{const p=new URLSearchParams(window.location.search);setFrom(p.get('report_from')||'');setTo(p.get('report_to')||'');setTopic(p.get('report_topic')||'All');setPublisher(p.get('report_publisher')||'All');setReady(true)};restore();window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore)},[]);
 useEffect(()=>{if(!ready)return;const url=new URL(window.location.href);for(const [key,value] of Object.entries({report_from:from,report_to:to,report_topic:topic==='All'?'':topic,report_publisher:publisher==='All'?'':publisher})){if(value)url.searchParams.set(key,value);else url.searchParams.delete(key)}window.history.replaceState(null,'',url)},[ready,from,to,topic,publisher]);
 const revision=useMemo(()=>reportRevision(records),[records]);
 const topics=[...new Set(records.map(r=>r.topic).filter(Boolean))].sort(),publishers=[...new Set(records.map(r=>r.publisher))].sort();
 const months=[...new Set(records.map(publicationMonth).filter(Boolean))].sort().reverse();
 const selectedMonth=from&&from.endsWith('-01')&&to===from.slice(0,7)+'-'+String(new Date(Number(from.slice(0,4)),Number(from.slice(5,7)),0).getDate())?from.slice(0,7):'';
 const key=[from,to,topic,publisher,revision].join('|');
 const invalid=Boolean(from&&to&&from>to);
 const rows=useMemo(()=>invalid?[]:records.filter(r=>{const month=publicationMonth(r);if(!month)return false;const day=r.datePrecision==='month'?'':r.date;const dateMatches=day?(!from||day>=from)&&(!to||day<=to):(!from||month>=from.slice(0,7))&&(!to||month<=to.slice(0,7));return dateMatches&&(topic==='All'||r.topic===topic)&&(publisher==='All'||r.publisher===publisher)}),[records,from,to,topic,publisher,invalid]);
 useEffect(()=>()=>{if(file)URL.revokeObjectURL(file.url)},[file]);
 async function prepare(){setBusy(true);setError('');try{const {coverageWorkbook}=await import('./monthly-report');const bytes=await coverageWorkbook(rows,`${from||'Earliest'} to ${to||'Latest'}; topic: ${topic}; publisher: ${publisher}`);setFile({url:URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),key})}catch{setError('Unable to prepare the report. Please try again.')}finally{setBusy(false)}}
 return <section id="reports" className="coverage-desk" aria-labelledby="report-builder-title"><p className="kicker">REPORTS</p><h2 id="report-builder-title">Build a coverage report</h2><div className="desk-controls"><label>Month<select value={selectedMonth} onChange={e=>{const m=e.target.value;if(!m){setFrom('');setTo('');return}setFrom(m+'-01');setTo(m+'-'+String(new Date(Number(m.slice(0,4)),Number(m.slice(5,7)),0).getDate()))}}><option value="">Custom range / all dates</option>{months.map(m=><option key={m} value={m}>{m}</option>)}</select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Report topic<select value={topic} onChange={e=>setTopic(e.target.value)}><option>All</option>{topics.map(v=><option key={v}>{v}</option>)}</select></label><label>Report publisher<select value={publisher} onChange={e=>setPublisher(e.target.value)}><option>All</option>{publishers.map(v=><option key={v}>{v}</option>)}</select></label></div><p>{rows.length} coverage items selected.</p><p className="desk-note">Includes articles, unlinked clippings and e-paper issues; profile and index pages are excluded. Missing dates are excluded; month-only issues are included when their month overlaps the chosen range. For a monthly report, choose that month’s first and last day.</p>{invalid&&<p role="alert">The start date must be on or before the end date.</p>}<button disabled={busy||invalid||!rows.length} onClick={prepare}>{busy?'Preparing…':'Prepare Excel report'}</button>{file?.key===key&&<p><a href={file.url} download="MCCIA-coverage-report.xlsx">Download Excel report</a></p>}<p role="status">{error}</p></section>;
}
