import { index, integer, real, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const clippingUploads = sqliteTable(
  'clipping_uploads',
  {
    id: text('id').primaryKey(),
    sha256: text('sha256').notNull(),
    uploadedAt: text('uploaded_at').notNull(),
    originalFilename: text('original_filename').notNull(),
    originalKey: text('original_key').notNull(),
    enhancedKey: text('enhanced_key').notNull(),
    originalContentType: text('original_content_type').notNull(),
    enhancedContentType: text('enhanced_content_type').notNull(),
    originalSize: integer('original_size').notNull(),
    enhancedSize: integer('enhanced_size').notNull(),
    width: integer('width').notNull(),
    height: integer('height').notNull(),
    publisher: text('publisher').notNull(),
    publicationDate: text('publication_date').notNull(),
    page: text('page'),
    language: text('language').notNull(),
    headline: text('headline').notNull(),
    ocrText: text('ocr_text').notNull(),
    ocrConfidence: real('ocr_confidence'),
    ocrLanguages: text('ocr_languages').notNull(),
    presence: text('presence').notNull(),
    status: text('status').notNull(),
    reviewed: integer('reviewed', { mode: 'boolean' }).notNull(),
    notes: text('notes').notNull(),
    sourceUrl: text('source_url'),
  },
  (table) => [
    uniqueIndex('idx_clipping_uploads_sha256').on(table.sha256),
    index('idx_clipping_uploads_publication_date').on(table.publicationDate),
    index('idx_clipping_uploads_publisher').on(table.publisher),
    index('idx_clipping_uploads_uploaded_at').on(table.uploadedAt),
  ],
);

export const googleFormIntake = sqliteTable(
  'google_form_intake',
  {
    id: text('id').primaryKey(),
    sha256: text('sha256').notNull(),
    receivedAt: text('received_at').notNull(),
    formTimestamp: text('form_timestamp'),
    formResponseId: text('form_response_id'),
    driveFileId: text('drive_file_id'),
    driveFileUrl: text('drive_file_url'),
    driveFolderUrl: text('drive_folder_url'),
    sheetRow: integer('sheet_row'),
    submitterEmail: text('submitter_email'),
    originalFilename: text('original_filename').notNull(),
    originalKey: text('original_key').notNull(),
    originalContentType: text('original_content_type').notNull(),
    originalSize: integer('original_size').notNull(),
    publicationDate: text('publication_date').notNull(),
    publisher: text('publisher').notNull(),
    page: text('page'),
    language: text('language').notNull(),
    headline: text('headline').notNull(),
    presence: text('presence').notNull(),
    notes: text('notes').notNull(),
    sourceUrl: text('source_url'),
    status: text('status').notNull(),
    errorMessage: text('error_message'),
    approvedAt: text('approved_at'),
    approvedRecordId: text('approved_record_id'),
  },
  (table) => [
    uniqueIndex('idx_google_form_intake_sha256').on(table.sha256),
    uniqueIndex('idx_google_form_intake_drive_file_id').on(table.driveFileId),
    index('idx_google_form_intake_status_received_at').on(table.status, table.receivedAt),
    index('idx_google_form_intake_publication_date').on(table.publicationDate),
    index('idx_google_form_intake_publisher').on(table.publisher),
  ],
);
