import type {JsonWebKey} from 'node:crypto';
import {zohoConfig,consumeZoho,verifyZohoToken} from '../../zoho';
import {zohoSession} from '../../access';
export const runtime='nodejs';export const dynamic='force-dynamic';
export async function GET(request:Request){
 if(process.env.NODE_ENV!=='development')return Response.redirect(new URL('/work-tracker/sign-in',request.url),303);
 const headers=new Headers({'Cache-Control':'no-store','Referrer-Policy':'no-referrer'});headers.append('Set-Cookie','wt_zoho_state=; HttpOnly; SameSite=Lax; Path=/api/work-tracker/zoho; Max-Age=0');
 
 try{const c=zohoConfig(),url=new URL(request.url);if(!c.ready||request.headers.get('host')!==new URL(c.redirect).host)throw Error();const cookie=request.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith('wt_zoho_state='))?.slice(14)||'';const flow=consumeZoho(url.searchParams.get('state')||'',cookie);const code=url.searchParams.get('code');if(url.searchParams.has('error')||!code)throw Error();
 const response=await fetch(c.host+'/oauth/v2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.client,client_secret:c.secret,redirect_uri:c.redirect,code,grant_type:'authorization_code',code_verifier:flow.verifier}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error();const tokens=await response.json() as {id_token?:string};if(typeof tokens.id_token!=='string')throw Error();
 const metadata=await fetch(c.host+'/.well-known/openid-configuration',{signal:AbortSignal.timeout(10000)});if(!metadata.ok)throw Error();const discovery=await metadata.json() as {issuer:string;jwks_uri:string};if(discovery.issuer!==c.host||new URL(discovery.jwks_uri).origin!==c.host)throw Error();const keyResponse=await fetch(discovery.jwks_uri,{signal:AbortSignal.timeout(10000)});if(!keyResponse.ok)throw Error();const keys=await keyResponse.json() as {keys:JsonWebKey[]};const user=verifyZohoToken(tokens.id_token,keys.keys,c.client,discovery.issuer,flow.nonce);const role=c.members[user.email];if(!role)throw Error();const session=await zohoSession(user.subject,user.name,role);headers.append('Set-Cookie',`wt_session=${session}; HttpOnly; SameSite=Strict; Path=/api/work-tracker; Max-Age=28800`);headers.set('Location','/work-tracker');return new Response(null,{status:303,headers});
 }catch{headers.set('Content-Type','text/html; charset=utf-8');return new Response('<h1>Sign-in could not be completed</h1><p>Try again, or ask your administrator to check your approved email, Zoho data centre and application settings.</p><a href="/work-tracker/sign-in">Return to work tracker</a>',{status:400,headers});}
}
