import {useState} from 'react';
import {actionsFor,stages,type WorkItem} from './model';
export default function ItemExtras({item,update,act,disabled,role}:{item:WorkItem;update:(key:keyof WorkItem,value:string)=>void;act:(extra:Record<string,unknown>)=>Promise<void>;disabled:boolean;role:string}){
 const [comment,setComment]=useState(''),[name,setName]=useState(''),[url,setUrl]=useState(''),[version,setVersion]=useState(''),[kind,setKind]=useState('Working document');
 const field=(key:keyof WorkItem,label:string,type='text')=><label key={key}>{label}<input type={type} value={String(item[key]||'')} onChange={e=>update(key,e.target.value)}/></label>;
 const recorded=new Set(item.history.filter(h=>h.fromStage&&h.toStage&&stages[item.category].indexOf(h.toStage)>stages[item.category].indexOf(h.fromStage)&&!['On hold','Needs confirmation'].includes(h.toStage)).map(h=>h.fromStage));
 const flow=stages[item.category].filter(s=>!['Needs confirmation','On hold'].includes(s)),index=flow.indexOf(item.stage);
 return <>
 <section className="wt-timeline" aria-label="Progress timeline"><h3>Progress timeline</h3><p>Only recorded transitions confirm completed stages. Imported status does not prove earlier work was completed.</p><ol>{flow.map((s,i)=><li key={s} className={s===item.stage?'current':recorded.has(s)?'recorded':''}><span>{s}</span><small>{s===item.stage?'Current':recorded.has(s)?'Recorded completion':i===index+1?'Next':'Not recorded'}</small></li>)}</ol>{index<0&&<p>Current: {item.stage}. Confirm the stage to establish what comes next.</p>}</section>
 <fieldset><legend>Assignment and publication</legend><div className="wt-form-grid">{field('reviewer','Reviewer')}<label>Priority<select value={item.priority||'Normal'} onChange={e=>update('priority',e.target.value)}>{['Low','Normal','High','Urgent'].map(x=><option key={x}>{x}</option>)}</select></label>{field('publicationDate','Publication date','date')}</div></fieldset>
 {item.category==='Sampada'&&<fieldset><legend>Sampada issue</legend><div className="wt-form-grid">{field('issueMonth','Issue month and year','month')}{field('theme','Theme')}</div></fieldset>}
 {item.category==='Representations'&&<fieldset><legend>Acknowledgement and follow-up</legend><div className="wt-form-grid">{field('acknowledgementDate','Acknowledgement date','date')}{field('followUpDate','Follow-up date','date')}</div></fieldset>}
 {item.category==='Distribution'&&<fieldset><legend>Delivery details</legend><div className="wt-form-grid">{field('quantity','Quantity','number')}{field('deliveryMethod','Delivery method')}{field('receiptDate','Receipt confirmed on','date')}</div></fieldset>}
 <fieldset><legend>Documents and versions</legend><p>Add accessible Drive or WorkDrive links. Each saved version retains its contributor and date; existing versions are kept.</p>{item.workingUrl&&<p><a href={item.workingUrl} target="_blank" rel="noreferrer">Open working document ↗</a></p>}{(item.documents||[]).map(d=><div className="wt-document" key={d.id}><a href={d.url} target="_blank" rel="noreferrer">{d.name} ↗</a><small>{d.kind} · {d.version} · {d.addedBy} · {new Date(d.addedAt).toLocaleDateString('en-IN')}</small></div>)}<div className="wt-form-grid"><label>Document name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Version<input placeholder="v1, v2, final…" value={version} onChange={e=>setVersion(e.target.value)}/></label><label>Type<select value={kind} onChange={e=>setKind(e.target.value)}>{['Working document','Final PDF','Supporting file'].map(x=><option key={x}>{x}</option>)}</select></label><label>File link<input type="url" value={url} onChange={e=>setUrl(e.target.value)}/></label></div><button type="button" disabled={disabled||!name||!version||!url} onClick={()=>void act({newDocument:{name,url,version,kind},comment})}>Save document version</button></fieldset>
 {item.source&&<label>Import review note<textarea value={item.resolutionNote||''} onChange={e=>update('resolutionNote',e.target.value)} placeholder="Explain the confirmed status, owner and dates; record what remains unknown."/></label>}
 <fieldset><legend>Workflow actions</legend><label>Comment<textarea rows={2} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Context for this update; required when requesting changes"/></label><div className="wt-actions">{actionsFor(item).map(action=><button type="button" key={action} disabled={disabled||!item.id||(role==='Editor'&&(action.startsWith('Approve')||action==='Request changes'))} onClick={()=>void act({action,comment})}>{action}</button>)}<button type="button" disabled={disabled||!comment.trim()||!item.id} onClick={()=>void act({comment})}>Record comment</button></div><p>Actions save the current details and record your identity. Printing, website upload and distribution remain separate.</p></fieldset>
 </>;
}
