'use client';
import {useEffect,useRef,useState} from 'react';
import {categories,stages,deliveryStates,blankItem,complete,overdue,indiaToday,attentionReasons,type Category,type WorkItem} from './model';
import './tracker.css';
import ItemExtras from './ItemExtras';
import TeamAccess,{type Access} from './TeamAccess';

export default function WorkTracker(){
 const [items,setItems]=useState<WorkItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [category,setCategory]=useState<Category>('Publications'),[query,setQuery]=useState(''),[stage,setStage]=useState('All'),[owner,setOwner]=useState('All'),[focus,setFocus]=useState('All'),[view,setView]=useState('list');
 const [draft,setDraft]=useState<WorkItem|null>(null),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(''),[notice,setNotice]=useState('');
 const [access,setAccess]=useState<Access>({configured:false,user:null,users:[]}),[scope,setScope]=useState('All work');
 const dialog=useRef<HTMLDialogElement>(null);
 async function load(quiet=false){if(!quiet)setLoading(true);setError('');try{const ar=await fetch('/api/work-tracker/access',{cache:'no-store'});const ad=await ar.json() as Access&{error?:string};if(!ar.ok)throw Error(ad.error||'Access settings unavailable.');setAccess(ad);if(!ad.user){setItems([]);return;}const response=await fetch('/api/work-tracker',{cache:'no-store'});const data=await response.json() as {items?:WorkItem[];error?:string};if(!response.ok||!Array.isArray(data.items))throw Error(data.error||'Could not load the tracker.');setItems(data.items)}catch(e){setError(e instanceof Error?e.message:'Could not load the tracker.')}finally{setLoading(false)}}
 useEffect(()=>{void load();const params=new URLSearchParams(window.location.search);const c=params.get('category');if(categories.includes(c as Category))setCategory(c as Category);if(params.get('view')==='board')setView('board');if(['All work','My work','Needs attention','Import review'].includes(params.get('scope')||''))setScope(params.get('scope')!);if(params.get('focus'))setFocus(params.get('focus')!)},[]);
 useEffect(()=>{const timer=window.setInterval(()=>{if(!draft)void load(true)},30000);return ()=>window.clearInterval(timer)},[Boolean(draft)]);
 useEffect(()=>{if(draft&&!dialog.current?.open)dialog.current?.showModal()},[draft]);
 function choose(c:Category){setScope('All work');setCategory(c);setStage('All');setFocus('All');setOwner('All');const p=new URLSearchParams({category:c,view});window.history.replaceState(null,'',`?${p}`)}
 function edit(item:WorkItem){setDraft(structuredClone(item));setSaveError('')}
 function close(){if(saving)return;dialog.current?.close();setDraft(null)}
 function update(key:keyof WorkItem,value:string){setDraft(d=>d?{...d,[key]:value}:d)}
 async function save(extra:Record<string,unknown>={}){if(!draft)return;setSaving(true);setSaveError('');try{const response=await fetch('/api/work-tracker',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,...extra})});const data=await response.json() as {item?:WorkItem;error?:string};if(!response.ok||!data.item)throw Error(data.error||'Could not save.');const item=data.item;setItems(all=>all.some(x=>x.id===item.id)?all.map(x=>x.id===item.id?item:x):[item,...all]);setNotice(`Saved “${item.title}” on this computer.`);dialog.current?.close();setDraft(null)}catch(e){setSaveError(e instanceof Error?e.message:'Could not save.')}finally{setSaving(false)}}
 const today=indiaToday();
 const group=items.filter(x=>(scope==='All work'?x.category===category:scope==='My work'?(x.owner.toLowerCase()===access.user?.name.toLowerCase()||x.reviewer?.toLowerCase()===access.user?.name.toLowerCase()):scope==='Needs attention'?attentionReasons(x,today).length>0:Boolean(x.source&&(!x.sourceConfirmed||!x.owner||!x.dueDate))));
 const filtered=group.filter(x=>(stage==='All'||x.stage===stage)&&(owner==='All'||(owner==='Unassigned'?!x.owner:x.owner===owner))&&(!query||`${x.title} ${x.owner} ${x.recipient} ${x.notes}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()))&&(focus==='All'||(focus==='Completed'?complete(x):focus==='Review'?attentionReasons(x,today).includes('Pending review'):attentionReasons(x,today).includes(focus))));
 const metric=(label:string,count:number,value:string)=><button className={focus===value?'selected':''} onClick={()=>setFocus(f=>f===value?'All':value)}><span>{label}</span><strong>{loading||error?'—':count}</strong></button>;
 const date=(value:string)=>value?new Date(value+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'Not set';
 const badge=(item:WorkItem)=><span className={`wt-stage ${complete(item)?'done':item.stage==='On hold'?'hold':''}`}>{item.stage}</span>;
 return <div className="wt-root"><header className="wt-header"><a href="/" className="brand"><img src="/mccia-logo.png" alt="MCCIA"/><span>Media Intelligence</span></a><nav aria-label="Tracker navigation"><a href="/">Media archive</a><a href="/work-tracker" aria-current="page">Work tracker</a></nav><span className="wt-local">Local workspace</span></header>
 <main className="wt-main"><div className="wt-heading"><div><p className="wt-eyebrow">MCCIA · EDITORIAL WORK</p><h1>From concept to publication.</h1><p>One place for reports, issues, press coverage and follow-ups.</p></div><button disabled={!access.user||access.user.role==='Viewer'} className="wt-primary" onClick={()=>edit(blankItem(category))}>＋ New item</button></div>
 <div className="wt-scope"><span>Local preview · Changes are saved on this computer.</span><span>Nothing is sent to the public website.</span></div>
 {!loading&&<TeamAccess access={access} refresh={load}/>}
 <div className="wt-view-tabs" aria-label="Work views">{['All work','My work','Needs attention','Import review'].map(label=><button key={label} aria-pressed={scope===label} onClick={()=>{setScope(label);setFocus('All');setStage('All');setOwner('All');window.history.replaceState(null,'',`?${new URLSearchParams({category,view,scope:label})}`)}}>{label}</button>)}</div>
 {scope!=='All work'&&<p className="wt-footnote">{scope==='My work'?`Assigned to ${access.user?.name||'you'} as owner or reviewer, across all categories.`:scope==='Import review'?'Resolve original statuses, missing owners and dates across all sheets. Open an item to compare original cells, enter corrections and record a review note.':'Across all categories: overdue work, missing deadlines, upcoming dates, reviews and follow-ups.'}</p>}
 <div className="wt-tabs" role="tablist" aria-label="Work categories">{categories.map(c=><button role="tab" aria-selected={category===c} key={c} onClick={()=>choose(c)}>{c}<span>{loading||error?'—':items.filter(x=>x.category===c).length}</span></button>)}</div>
 <div className="wt-metrics">{metric('Total items',group.length,'All')}{metric('Awaiting review',group.filter(x=>['Review','Proofreading','Final approval'].includes(x.stage)).length,'Review')}{metric('Overdue',group.filter(x=>overdue(x,today)).length,'Overdue')}{metric('Unassigned',group.filter(x=>attentionReasons(x,today).includes('Unassigned')).length,'Unassigned')}{metric('No deadline',group.filter(x=>!x.dueDate&&!complete(x)).length,'No deadline')}{metric('Due this week',group.filter(x=>attentionReasons(x,today).includes('Due this week')).length,'Due this week')}</div>
 <section className="wt-work"><div className="wt-tools"><label className="wt-search">Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a title, person or recipient…"/></label><label>Stage<select value={stage} onChange={e=>setStage(e.target.value)}><option>All</option>{[...new Set(group.flatMap(x=>stages[x.category]))].map(s=><option key={s}>{s}</option>)}</select></label><label>Owner<select value={owner} onChange={e=>setOwner(e.target.value)}><option>All</option><option>Unassigned</option>{[...new Set(group.map(x=>x.owner).filter(Boolean))].sort().map(x=><option key={x}>{x}</option>)}</select></label><label>Attention<select value={focus} onChange={e=>{setFocus(e.target.value);window.history.replaceState(null,'',`?${new URLSearchParams({category,view,scope,focus:e.target.value})}`)}}>{['All','Overdue','No deadline','Due this week','Review','Unassigned','Follow-up due','Import review','Completed'].map(f=><option key={f}>{f}</option>)}</select></label><div className="wt-switch" aria-label="View">{['list','board'].map(v=><button key={v} aria-pressed={view===v} onClick={()=>{setView(v);window.history.replaceState(null,'',`?${new URLSearchParams({category,view:v,scope,focus})}`)}}>{v==='list'?'List':'Board'}</button>)}</div></div>
 <div className="wt-results"><button onClick={()=>void load()} disabled={loading}>Refresh</button><strong>{scope==='All work'?category:scope}</strong><span>{loading?'Loading…':`${filtered.length} items${focus!=='All'?` · ${focus}`:''}`}</span>{focus!=='All'&&<button onClick={()=>setFocus('All')}>Clear selection</button>}</div>
 {notice&&<p className="wt-notice" role="status">{notice}</p>}{!access.user&&!loading&&!error?<div className="wt-empty">Sign in above to view team work.</div>:error?<div className="wt-empty" role="alert"><h2>Tracker unavailable</h2><p>{error}</p><button onClick={()=>void load()}>Retry</button></div>:loading?<p className="wt-empty">Loading your local workspace…</p>:!filtered.length?<div className="wt-empty"><h2>No items here yet</h2><p>Try another filter or add a new item.</p></div>:scope==='Import review'?<div className="wt-import-list">{filtered.map(item=><article key={item.id}><div><span className="wt-eyebrow">{item.category} · row {item.source?.row}</span><h3>{item.title}</h3><p>Current stage: {item.stage} · Owner: {item.owner||'Unassigned'} · Deadline: {item.dueDate||'Not set'}</p><ul>{!item.sourceConfirmed&&item.flags.map(f=><li key={f}>{f}</li>)}{!item.owner&&<li>Assign an owner</li>}{!item.dueDate&&<li>Confirm a deadline or document why no deadline applies</li>}</ul>{item.resolutionNote&&<p>Last review note: {item.resolutionNote}</p>}<details><summary>Original spreadsheet values</summary><dl>{Object.entries(item.source?.cells||{}).map(([cell,value])=><div key={cell}><dt>{cell}</dt><dd>{value}</dd></div>)}</dl></details></div><button onClick={()=>edit(item)}>Review item</button></article>)}</div>:view==='list'?<div className="wt-table-wrap"><table className="wt-table"><thead><tr><th>Item</th><th>Stage</th><th>Owner</th><th>Due date</th><th>Next action</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><button className="wt-title" onClick={()=>edit(item)}>{item.title}</button>{scope!=='All work'&&<small>{item.category}</small>}{item.priority&&item.priority!=='Normal'&&<small>{item.priority} priority</small>}{item.recipient&&<small>{item.recipient}</small>}{item.flags.length>0&&!item.sourceConfirmed&&<small className="wt-review">Source details need confirmation</small>}</td><td>{badge(item)}</td><td>{item.owner||<span className="wt-muted">Unassigned</span>}</td><td className={overdue(item,today)?'wt-overdue':''}>{item.dueDate?date(item.dueDate):'No deadline'}{overdue(item,today)&&<small>Overdue</small>}</td><td>{item.nextAction||<span className="wt-muted">Not set</span>}</td></tr>)}</tbody></table></div>:<div className="wt-board">{[...new Set(filtered.flatMap(x=>stages[x.category]))].filter(s=>filtered.some(x=>x.stage===s)).map(s=><section className="wt-column" key={s}><h3>{s}<span>{filtered.filter(x=>x.stage===s).length}</span></h3>{filtered.filter(x=>x.stage===s).map(item=><button className="wt-board-card" key={item.id} onClick={()=>edit(item)}><strong>{item.title}</strong><span>{item.owner||'Unassigned'}</span>{item.nextAction&&<p>{item.nextAction}</p>}<small className={overdue(item,today)?'wt-overdue':''}>{item.dueDate?date(item.dueDate):'No deadline set'}</small></button>)}</section>)}</div>}
 </section><p className="wt-footnote">Imported from Media.xlsx. Original notes are retained inside each item. “Yes” and “Done” have not been treated as proof of publication.</p></main>
 <dialog ref={dialog} className="wt-dialog" onCancel={e=>{e.preventDefault();close()}}>{draft&&<form onSubmit={e=>{e.preventDefault();void save()}}><div className="wt-dialog-head"><div><p className="wt-eyebrow">{draft.category}</p><h2>{draft.id?'Item details':'Create an item'}</h2></div><button type="button" onClick={close} disabled={saving} aria-label="Close item">✕</button></div><div className="wt-dialog-body"><fieldset disabled={saving||access.user?.role==='Viewer'} className="wt-edit-fields"><label>Title<input required maxLength={1000} value={draft.title} onChange={e=>update('title',e.target.value)}/></label><div className="wt-form-grid"><label>Stage<select value={draft.stage} onChange={e=>update('stage',e.target.value)}>{stages[draft.category].map(s=><option key={s}>{s}</option>)}</select></label><label>Owner<input placeholder="Assign a team member" value={draft.owner} onChange={e=>update('owner',e.target.value)}/></label><label>Deadline<input type="date" value={draft.dueDate} onChange={e=>update('dueDate',e.target.value)}/></label><label>Next action<input value={draft.nextAction} onChange={e=>update('nextAction',e.target.value)} placeholder="What needs to happen next?"/></label></div><label>Working document link<input type="url" value={draft.workingUrl} onChange={e=>update('workingUrl',e.target.value)} placeholder="https://…"/></label><ItemExtras key={draft.id||'new'} item={draft} update={update} act={save} disabled={saving||access.user?.role==='Viewer'} role={access.user?.role||'Viewer'}/><label>Notes<textarea rows={5} value={draft.notes} onChange={e=>update('notes',e.target.value)}/></label>
 <fieldset><legend>Release and delivery</legend><p>Track each activity separately. These fields record progress; they do not publish or send files.</p><div className="wt-form-grid">{(['printStatus','websiteStatus','distributionStatus'] as const).map((key,i)=><label key={key}>{['Printing','Website upload','Distribution'][i]}<select value={draft[key]} onChange={e=>update(key,e.target.value)}>{deliveryStates.map(s=><option key={s}>{s}</option>)}</select></label>)}<label>Published link<input type="url" value={draft.publishedUrl} onChange={e=>update('publishedUrl',e.target.value)} placeholder="https://…"/></label></div></fieldset>
 {['Distribution','Representations','News & press releases'].includes(draft.category)&&<fieldset><legend>Recipients and follow-up</legend><div className="wt-form-grid"><label>Recipient / publisher<input value={draft.recipient} onChange={e=>update('recipient',e.target.value)}/></label><label>Sent date<input type="date" value={draft.sentDate} onChange={e=>update('sentDate',e.target.value)}/></label></div><label>Response / acknowledgement<textarea rows={3} value={draft.response} onChange={e=>update('response',e.target.value)}/></label></fieldset>}
 {draft.flags.length>0&&<div className="wt-flags"><strong>Check the imported details</strong><ul>{draft.flags.map(f=><li key={f}>{f}</li>)}</ul><label className="wt-confirm"><input type="checkbox" checked={Boolean(draft.sourceConfirmed)} onChange={e=>setDraft(d=>d?{...d,sourceConfirmed:e.target.checked}:d)}/>I have checked these source details and updated this item.</label></div>}
 {draft.source&&<details className="wt-original"><summary>Original workbook values · {draft.source.sheet}, row {draft.source.row}</summary><dl>{Object.entries(draft.source.cells).map(([cell,value])=><div key={cell}><dt>{cell}</dt><dd>{value}</dd></div>)}</dl></details>}
 <details className="wt-original"><summary>Update history ({draft.history.length})</summary><ol>{[...draft.history].reverse().map((h,i)=><li key={i}><strong>{h.at?new Date(h.at).toLocaleString('en-IN'):'Workbook import'}</strong><p>{h.actor||'Imported record · actor not recorded'} · {h.summary}</p>{h.comment&&<p>{h.comment}</p>}</li>)}</ol></details>
 </fieldset></div><div className="wt-dialog-footer">{saveError&&<p role="alert">{saveError}</p>}<button type="button" onClick={close} disabled={saving}>Cancel</button><button className="wt-primary" disabled={saving||access.user?.role==='Viewer'}>{saving?'Saving…':'Save changes'}</button></div></form>}</dialog></div>;
}
