import {assemble,counts} from './model.js';
const $=id=>document.getElementById(id),fmt=n=>n.toLocaleString('en-IN');let snapshot,model,busy=false;
const filters=['kind','year','publisher','language'];
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
function stamp(value){return value?new Date(value).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'Unavailable';}
function bars(id,entries,total){const box=$(id);box.replaceChildren();if(!entries.length){box.append(el('p','No matching coverage.','note'));return;}const max=Math.max(...entries.map(e=>e[1]),1);for(const [label,value] of entries){const row=el('div',undefined,'bar-row'),caption=el('div',undefined,'bar-label');caption.append(el('span',label),el('b',`${fmt(value)}${total?' · '+Math.round(value/total*100)+'%':''}`));const track=el('div',undefined,'track'),fill=el('div',undefined,'fill');fill.style.width=(value/max*100)+'%';track.append(fill);row.append(caption,track);box.append(row);}}
function top(rows,key,n=7){const entries=counts(rows,key);if(entries.length<=n)return entries;return [...entries.slice(0,n),['Other categories',entries.slice(n).reduce((a,b)=>a+b[1],0)]];}
function publication(r){if(r.datePrecision==='month'||r.publicationMonth)return String(r.publicationMonth||r.date?.slice(0,7)||r.year||'Date unavailable');return r.date||String(r.year||'Date unavailable');}
function render(){if(!model)return;const rows=model.rows.filter(r=>filters.every(key=>!$(key).value||String(r[key]||'Date unavailable')===$(key).value));
 const metrics=[['Coverage items',rows.length,'Linked evidence excluded'],['Media records',rows.filter(r=>r.kind==='Media record').length,'Structured article entries'],['E-paper entries',rows.filter(r=>r.kind==='E-paper').length,'Includes month-only issues'],['Unlinked clippings',rows.filter(r=>r.kind==='Unlinked clipping').length,'Additional archived evidence']];
 $('metrics').replaceChildren(...metrics.map(([label,value,note])=>{const card=el('div',undefined,'metric');card.append(el('span',label),el('strong',fmt(value)),el('small',note));return card;}));
 $('method').textContent=`${fmt(model.clippings.length)} clippings in the full archive; ${fmt(model.linked)} are connected to media records and are not added again to coverage totals. Counts above follow the selected filters.`;
 for(const [id,key] of [['publishers','publisher'],['topics','topic'],['people','person'],['languages','language'],['dg','dg']])bars(id,top(rows,key),rows.length);
 const noDate=rows.filter(r=>!r.date||!r.year).length;
 bars('quality',[['No exact publication date',rows.filter(r=>!r.date||!r.year||r.datePrecision==='month'||r.publicationMonth).length],['Year unavailable',rows.filter(r=>!r.year).length],['Language not recorded',rows.filter(r=>r.language==='Language not recorded').length],['Full archive: OCR not requested',model.clippings.filter(r=>/not requested/i.test(r.ocrStatus||'')).length],['Full archive: ambiguous matches',model.clippings.filter(r=>/ambiguous/i.test(r.matchStatus||'')).length]],0);
 let periods;if($('period').value==='year')periods=counts(rows,r=>r.year||'Unavailable').sort((a,b)=>a[0].localeCompare(b[0]));else{const today=new Date();const months=Array.from({length:12},(_,i)=>{const d=new Date(Date.UTC(today.getFullYear(),today.getMonth()-11+i,1));return d.toISOString().slice(0,7);});const c=new Map(counts(rows,r=>r.publicationMonth||r.date?.slice(0,7)||''));periods=months.map(m=>[m,c.get(m)||0]);}
 const max=Math.max(...periods.map(p=>p[1]),1);$('trend').replaceChildren(...periods.map(([label,value])=>{const node=el('div',undefined,'column'),bar=el('i');bar.style.height=(value/max*165)+'px';node.append(el('b',fmt(value)),bar,el('span',label));node.title=label+': '+fmt(value);return node;}));
 $('trend-note').textContent=$('period').value==='month'?`Monthly view uses recorded publication months. Undated and year-only items are excluded; it shows publication activity, not upload activity.`:`${fmt(noDate)} items have no valid exact date. Year-only records remain in their known year.`;
 $('result-count').textContent=`Latest 15 of ${fmt(rows.length)} matching items`;
 const latest=rows.filter(r=>r.year&&(r.date||r.publicationMonth)).sort((a,b)=>String(b.publicationMonth||b.date).localeCompare(String(a.publicationMonth||a.date))).slice(0,15);
 $('recent').replaceChildren(...latest.map(r=>{const tr=el('tr'),title=el('td');let link;try{const u=new URL(r.url,snapshot.origin);if(r.url&&u.protocol==='https:'&&!u.username&&!u.password)link=u.href;}catch{}if(link){const a=el('a',r.title||'Headline unavailable');a.href=link;a.target='_blank';a.rel='noopener noreferrer';title.append(a);}else title.textContent=r.title||'Headline unavailable';tr.append(el('td',publication(r)),title,el('td',r.publisher),el('td',r.kind));return tr;}));if(!latest.length){const tr=el('tr'),td=el('td','No dated items match these filters.');td.colSpan=4;tr.append(td);$('recent').append(tr);}
 const params=new URLSearchParams();for(const key of filters)if($(key).value)params.set(key,$(key).value);if($('period').value!=='year')params.set('period',$('period').value);history.replaceState(null,'',location.pathname+(params.size?'?'+params:''));
}
async function refresh(){if(busy)return;busy=true;$('refresh').disabled=true;$('refresh').textContent='Refreshing…';try{const response=await fetch('/api/dashboard',{cache:'no-store'}),result=await response.json();if(!response.ok||!result.data)throw Error(result.error||'Connection unavailable');snapshot=result;model=assemble(snapshot);
 const params=new URLSearchParams(location.search);for(const key of filters){const selected=$(key).value||params.get(key)||'';const values=[...new Set(model.rows.map(r=>String(r[key]||'Date unavailable')))].sort((a,b)=>key==='year'?b.localeCompare(a):a.localeCompare(b));const first=$(key).options[0].cloneNode(true);$(key).replaceChildren(first,...values.map(v=>{const o=el('option',v);o.value=v;return o;}));$(key).value=values.includes(selected)?selected:'';}
 if(params.get('period')==='month')$('period').value='month';
 const failures=snapshot.connections.filter(c=>!c.ok),version=snapshot.connections.find(c=>c.name==='archive-version'&&c.ok)?.data?.version;
 const expected=`${snapshot.data['archive-metadata'].dataHash}:${snapshot.data['discovery-status'].checkedAt}`;
 $('health').textContent=snapshot.stale?'Last saved snapshot':failures.length?'Archive connected · partial live data':'Data connections available';
 $('checked').textContent=`Last successful check: ${stamp(snapshot.checkedAt)}. Archive updated: ${stamp(snapshot.data['archive-metadata'].updatedAt)}.`;
 $('notice').textContent=snapshot.stale?'Refresh failed. Showing the last successful snapshot; figures may be outdated.':`Published archive loaded.${failures.length?' '+failures.length+' live connection(s) unavailable; new uploads or corrections may be missing.':''} ${version===expected?'The website reports the same archive version.':'The published repository snapshot could not be confirmed as the website’s deployed version.'}`;
 const labels={'uploads':'Live clipping uploads','source-monitoring':'Live discovery records','corrections':'Published corrections','archive-version':'Website version'};
 $('connections').replaceChildren(...snapshot.connections.map(c=>{const node=el('div',undefined,'connection'+(c.ok?'':' bad'));node.append(el('strong',labels[c.name]),el('span',c.ok?'Connected':'Unavailable · '+c.error));return node;}));
 const audit=snapshot.data['source-verification'];const unreachable=Object.values(audit.records||{}).filter(r=>r.category==='unreachable').length;
 $('provenance').textContent=`Public archive snapshot ${snapshot.commit.slice(0,8)}. ${fmt(unreachable)} URLs were marked unreachable in the stored audit (${stamp(audit.generatedAt)}); these links were not retested by this dashboard. Metadata categories use the website’s normalization rules. Automatic refresh checks for published updates; it does not crawl the internet or trigger OCR.`;
 render();
 }catch(error){$('health').textContent='Connection unavailable';$('notice').textContent=error.message+(model?' Previous figures remain visible.':' Start this dashboard using start-dashboard.cmd; an internet connection is required.');}finally{busy=false;$('refresh').disabled=false;$('refresh').textContent='Refresh data';}}
 filters.forEach(key=>$(key).addEventListener('change',render));$('period').addEventListener('change',render);$('clear').onclick=()=>{filters.forEach(key=>$(key).value='');render();};$('refresh').onclick=refresh;setInterval(()=>{if($('auto').checked&&!document.hidden)refresh();},300000);refresh();
